apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest
          ports:
            - containerPort: 5672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: katrinconsole
            - name: RABBITMQ_DEFAULT_PASS
              value: $ipepdv$
            - name: HOSTNAME
              value: epics-rabbitmq
      triggers:
        - type: ConfigChange
