# Generated by Django 3.2.3 on 2021-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_legacycontrolidmappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdeiChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_server', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=100)),
                ('db_group', models.CharField(max_length=100)),
                ('chid', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('axis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdeiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_server', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=100)),
                ('db_group', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
