# Generated by Django 3.2.3 on 2021-07-03 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adeichannel_adeigroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeichannel',
            name='axis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adeichannel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adeichannel',
            name='uid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legacycontrolidmappings',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
