# Generated by Django 3.2.3 on 2021-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210703_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacycontrolidmappings',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
