# Generated by Django 3.2.3 on 2021-07-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_legacycontrolidmappings_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyControlBlockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('db_server', models.CharField(max_length=100)),
                ('block_id', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LegacyControlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('db_server', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=100)),
                ('cgroup_db_group', models.CharField(max_length=100)),
                ('cgroup_name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('block_id', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=200)),
                ('axis', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('read', models.CharField(max_length=20)),
                ('write', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
