# Generated by Django 3.2.3 on 2021-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_legacycontrolitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeichannel',
            name='chid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legacycontrolidmappings',
            name='katrin_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
