# Generated by Django 3.2.3 on 2021-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210705_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeichannel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
